### ISSUE TITLE
Simulator output assumes there is allways a single `gnbSim` instance

### ISSUE THREAD

**Issue by gab-arrobo** [opennetworkinglab/aether-gnbsim#10]
Currently, it is assumed that only a single instance of `gnbSim` is running and only the results for the first instance are displayed regardless of the number of `gnbSim` instances running as shown [here](https://github.com/opennetworkinglab/aether-gnbsim/blob/master/roles/simulator/tasks/start.yml#L65)
```
- name: show outupt of summary.log from gnbsim Pod
  shell: |
    docker exec gnbsim-1 cat summary.log
  register: gNbsimPod
  when: inventory_hostname in groups['gnbsim_nodes']
```

**Comment by llpeterson** [comment]
That’s right. It was a design choice. The OnRamp playbook displays the summary log for the first instance of gnbsim (the common case). The guide instructs users that configure multiple instances where to find the additional logs.
